CREATE TABLE "FURN"."CATEGORY"  (
		  "ID" VARCHAR(16) NOT NULL , 
		  "NAME" VARCHAR(50) NOT NULL , 
		  "DESCRIPTION" VARCHAR(100))   
		 IN "USERSPACE1" ; 


CREATE TABLE "FURN"."COLLECTION"  (
		  "ID" VARCHAR(16) NOT NULL , 
		  "NAME" VARCHAR(50) NOT NULL , 
		  "DESCRIPTION" VARCHAR(100) )   
		 IN "USERSPACE1" ; 


CREATE TABLE "FURN"."ITEM"  (
		  "ID" VARCHAR(16) NOT NULL , 
		  "NAME" VARCHAR(50) NOT NULL , 
		  "DETAILS" VARCHAR(100) NOT NULL , 
		  "KEYWORDS" VARCHAR(100) NOT NULL )   
		 IN "USERSPACE1" ; 


CREATE TABLE "FURN"."COLLECTION_CATEGORY_MAP"  (
		  "ID" VARCHAR(16) NOT NULL , 
		  "COLLECTION_ID" VARCHAR(16) NOT NULL , 
		  "CATEGORY_ID" VARCHAR(16) NOT NULL )   
		 IN "USERSPACE1" ; 
		 
CREATE TABLE "FURN"."ITEM_COLLECTION"  (
		  "ID" VARCHAR(16) NOT NULL , 
		  "ITEM_ID" VARCHAR(16) NOT NULL , 
		  "COLLECTION_CATEGORY_ID" VARCHAR(16) NOT NULL )   
		 IN "USERSPACE1" ; 



-- DDL Statements for primary key on Table "FURN"."CATEGORY"

ALTER TABLE "FURN"."CATEGORY" 
	ADD CONSTRAINT "CATEGORY_PRIMARY" PRIMARY KEY
		("ID");


-- DDL Statements for unique constraints on Table "FURN"."CATEGORY"


ALTER TABLE "FURN"."CATEGORY" 
	ADD CONSTRAINT "CATEGORY_UNIQUE_NAME" UNIQUE
		("NAME");
		
------------------------------------------------
-- DDL Statements for table "FURN"."COLLECTION"
------------------------------------------------


-- DDL Statements for primary key on Table "FURN"."COLLECTION"

ALTER TABLE "FURN"."COLLECTION" 
	ADD CONSTRAINT "COLLECTION_UNIQUE_NAME" PRIMARY KEY
		("ID");


-- DDL Statements for unique constraints on Table "FURN"."COLLECTION"


ALTER TABLE "FURN"."COLLECTION" 
	ADD CONSTRAINT "COLLECTION_PRIMARY" UNIQUE
		("NAME");


-- DDL Statements for primary key on Table "FURN"."ITEM"

ALTER TABLE "FURN"."ITEM" 
	ADD CONSTRAINT "ITEM_PRIMARY" PRIMARY KEY
		("ID");

ALTER TABLE "FURN"."ITEM" 
	ADD CONSTRAINT "ITEM_UNIQUE_NAME" UNIQUE
		("NAME");


ALTER TABLE "FURN"."COLLECTION_CATEGORY_MAP" 
	ADD CONSTRAINT "COLLECTION_CATEGORY_PRIMARY" PRIMARY KEY
		("ID");


ALTER TABLE "FURN"."COLLECTION_CATEGORY_MAP" 
	ADD CONSTRAINT "COLLECTION_CATEGORY_UNIQUE_COMBO" UNIQUE
		("COLLECTION_ID",
		 "CATEGORY_ID");

ALTER TABLE "FURN"."ITEM_COLLECTION" 
	ADD CONSTRAINT "CC1231986765656" PRIMARY KEY
		("ID");

