		
alter table CLICK_EVENT drop foreign key CLICK_EVENT_FK;		

alter table URL_EVENT drop foreign key URL_EVENT_FK;		
		
drop table if exists event;
drop table if exists click_event;
drop table if exists url_event;
		
		  
CREATE TABLE EVENT  (
		  EVENT_ID INTEGER NOT NULL AUTO_INCREMENT, 
		  CLIENT_ID VARCHAR(20) NOT NULL , 
		  IP VARCHAR(20) NOT NULL , 
		  USER_ID VARCHAR(30) , 
		  SESSION_ID VARCHAR(30) , 
		  TIME TIMESTAMP NOT NULL , 
		  TARGET_HIT VARCHAR(5),
		  PRIMARY KEY(EVENT_ID) )   
			;

-- ALTER TABLE EVENT ALTER COLUMN EVENT_ID RESTART WITH 1007;
			

CREATE TABLE CLICK_EVENT  (
		  EVENT_ID INTEGER NOT NULL , 
		  ELEM_ID VARCHAR(30) , 
		  ELEM_NAME VARCHAR(30) , 
		  ELEM_TYPE VARCHAR(30) , 
		  VALUE VARCHAR(30) )   
		 ;
		 
ALTER TABLE CLICK_EVENT 
	ADD CONSTRAINT CC1234013253687 PRIMARY KEY
		(EVENT_ID);
		 
		 
CREATE TABLE URL_EVENT  (
		  EVENT_ID INTEGER NOT NULL DEFAULT 20 , 
		  URL VARCHAR(300) NOT NULL )   
		 ; 

ALTER TABLE URL_EVENT 
	ADD CONSTRAINT CC1234013348546 PRIMARY KEY
		(EVENT_ID);
		 
ALTER TABLE URL_EVENT 
	ADD CONSTRAINT URL_EVENT_FK FOREIGN KEY (EVENT_ID)
	REFERENCES EVENT(EVENT_ID);

ALTER TABLE CLICK_EVENT 
	ADD CONSTRAINT CLICK_EVENT_FK FOREIGN KEY (EVENT_ID)
	REFERENCES EVENT(EVENT_ID);

		  